"""initial

Revision ID: 6baf413bf5e0
Revises: 
Create Date: 2026-04-01 06:58:27.025391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baf413bf5e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ein', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('date_founded', sa.Date(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('business_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('outstanding_debt', sa.Float(), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('owner_credit_score', sa.Integer(), nullable=True),
    sa.Column('is_real', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_risks_business_id'), 'business_risks', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_risks_id'), 'business_risks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_risks_id'), table_name='business_risks')
    op.drop_index(op.f('ix_business_risks_business_id'), table_name='business_risks')
    op.drop_table('business_risks')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
