"""split business risks into separate table

Revision ID: 7151d3c887d5
Revises: dc396f8fc0b1
Create Date: 2026-04-01 06:20:06.273814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7151d3c887d5'
down_revision: Union[str, None] = 'dc396f8fc0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('is_real', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_risks_business_id'), 'business_risks', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_risks_id'), 'business_risks', ['id'], unique=False)
    op.drop_column('businesses', 'risk_score')
    op.drop_column('businesses', 'is_real')
    op.drop_column('businesses', 'evaluated_at')
    op.drop_column('businesses', 'risk_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('risk_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('evaluated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('is_real', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_business_risks_id'), table_name='business_risks')
    op.drop_index(op.f('ix_business_risks_business_id'), table_name='business_risks')
    op.drop_table('business_risks')
    # ### end Alembic commands ###
