"""move employees and credit score to risks, years_in_business to date_founded

Revision ID: 781d11feadcf
Revises: 7151d3c887d5
Create Date: 2026-04-01 06:37:31.478098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781d11feadcf'
down_revision: Union[str, None] = '7151d3c887d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_risks', sa.Column('monthly_revenue', sa.Float(), nullable=True))
    op.add_column('business_risks', sa.Column('outstanding_debt', sa.Float(), nullable=True))
    op.add_column('business_risks', sa.Column('num_employees', sa.Integer(), nullable=True))
    op.add_column('business_risks', sa.Column('owner_credit_score', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('date_founded', sa.Date(), nullable=True))
    op.drop_column('businesses', 'outstanding_debt')
    op.drop_column('businesses', 'num_employees')
    op.drop_column('businesses', 'monthly_revenue')
    op.drop_column('businesses', 'years_in_business')
    op.drop_column('businesses', 'owner_credit_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('owner_credit_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('years_in_business', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('monthly_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('num_employees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('outstanding_debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'date_founded')
    op.drop_column('business_risks', 'owner_credit_score')
    op.drop_column('business_risks', 'num_employees')
    op.drop_column('business_risks', 'outstanding_debt')
    op.drop_column('business_risks', 'monthly_revenue')
    # ### end Alembic commands ###
