"""initial

Revision ID: dc396f8fc0b1
Revises: 
Create Date: 2026-04-01 00:34:04.134378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc396f8fc0b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_id', table_name='items')
    op.drop_table('items')
    op.add_column('businesses', sa.Column('ein', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('state', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('years_in_business', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('monthly_revenue', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('num_employees', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('outstanding_debt', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('owner_credit_score', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('risk_tier', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('evaluated_at', sa.DateTime(), nullable=True))
    op.drop_column('businesses', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'evaluated_at')
    op.drop_column('businesses', 'risk_tier')
    op.drop_column('businesses', 'risk_score')
    op.drop_column('businesses', 'owner_credit_score')
    op.drop_column('businesses', 'owner_name')
    op.drop_column('businesses', 'outstanding_debt')
    op.drop_column('businesses', 'num_employees')
    op.drop_column('businesses', 'monthly_revenue')
    op.drop_column('businesses', 'years_in_business')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'business_type')
    op.drop_column('businesses', 'ein')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    # ### end Alembic commands ###
